---

  - name: Maintenance for DokuWiki containers
    hosts: DOCKERHOST-PROD
    tasks:
    - name: Run the rebuild script for DOKUWIKI
      ansible.builtin.script: /Users/hank/Docker/wikis/music/bin/rebuild-music_wiki.sh 
#      shell:
#         "/Users/hank/Docker/wikis/music/bin/rebuild-music_wiki.sh"
#         "echo test"
      args: 
         executable: /bin/bash
      register: bashcmd
      tags: bashcmd

    - debug: msg="{{bashcmd.stdout}}"
