---

  - name: Maintenance for DokuWiki containers
    hosts: DOCKERHOST-PROD
    tasks:
    - name: Run the rebuild script for DOKUWIKI
      ansible.builtin.shell: "rebuild-music_wiki" 
      become: yes
      args: 
         executable: /bin/bash
      register: bashcmd
      tags: bashcmd

    - debug: msg="{{bashcmd.stdout}}"
