---

  - name: Maintenance for DokuWiki containers
    hosts: DOCKERHOST-PROD
    become: yes
    tasks:
    - name: Run the rebuild script for DOKUWIKI
      ansible.builtin.shell: "docker stop wiki_music" 
      args: 
         executable: /bin/bash
      register: bashcmd
      tags: bashcmd

    - debug: msg="{{bashcmd.stdout}}"
